export const FETCH_RENTALS = 'FETCH_RENTALS';
export const FETCH_RENTAL_BY_ID_SUCCESS = 'FETCH_RENTAL_BY_ID_SUCCESS';
export const FETCH_RENTALS_INIT = 'FETCH_RENTALS_INIT';

export const LOGIN_USER = 'LOGIN_USER';
export const REGISTER_USER = 'REGISTER_USER';

export const AUTH_ERROR = 'AUTH_ERROR';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const GET_ERRORS = 'GET_ERRORS';

export const RENTAL_CREATED = 'RENTAL_CREATED';

export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';

export const BOOKING_CREATED = 'BOOKING_CREATED';
export const USER_BOOKING_SUCCESS = 'USER_BOOKING_SUCCESS';
export const USER_RENTAL_SUCCESS = 'USER_RENTAL_SUCCESS';

export const RENTAL_DELETED_SUCCESS = 'RENTAL_DELETED_SUCCESS';
export const IMAGE_UPLOAD_SUCCESS = '  IMAGE_UPLOAD_SUCCESS';

export const UPDATE_RENTAL_SUCCESS = 'UPDATE_RENTAL_SUCCESS';

export const MAKE_PAYMENT_SUCCESS = 'MAKE_PAYMENT_SUCCESS';
export const PENDING_PAYMENTS_SUCCESS = 'PENDING_PAYMENTS_SUCCESS';

export const REVIEW_CREATED_SUCCESS = 'REVIEW_CREATED_SUCCESS';
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS';
export const GET_REVIEWS_AVG_SUCCESS = 'GET_REVIEWS_AVG_SUCCESS';

export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'